# action.yml
name: 'GitHub Action VPN'
author: 'Unknow.sk'
description: 'Establish OpenVPN, PPTP, L2TP, WireGuard, FortiClient or Cisco AnyConnect VPN connection on Github Actions.'
branding:
  icon: "shield"
  color: "gray-dark"
inputs:
  VPN_OS:
    description: 'Type of OS on which the commands will be executed. Supported "ubuntu" (default).'
    default: 'ubuntu'
    required: false
  VPN_TYPE:
    description: 'Type of VPN connection. Supported "pptp", "l2tp", "wireguard", "forticlient", "cisco", or "openvpn" (default).'
    default: 'openvpn'
    required: false
  VPN_USER:
    description: 'Username for VPN connection.'
    required: true
  VPN_PASSWORD:
    description: 'Password for VPN connection.'
    required: true
  VPN_SERVER:
    description: 'Host name or IP address of VPN server.'
    required: true
  VPN_PSK:
    description: 'Shared secret key for VPN connection. Required for L2TP.'
    required: false
  VPN_CONFIG:
    description: 'Content of VPN configuration file. Required for OpenVPN and WireGuard.'
    required: false
runs:
  steps:
    - name: Echo VPN Inputs
      run: |
        echo "${{ github.action_path }}" >> $GITHUB_ACTION_PATH
        echo "${{ inputs.VPN_OS }}" >> $VPN_OS
        echo "${{ inputs.VPN_TYPE }}" >> $VPN_TYPE
        echo "${{ inputs.VPN_USER }}" >> $VPN_USER
        echo "${{ inputs.VPN_PASSWORD }}" >> $VPN_PASSWORD
        echo "${{ inputs.VPN_SERVER }}" >> $VPN_SERVER
        echo "${{ inputs.VPN_PSK }}" >> $VPN_PSK
        echo "${{ inputs.VPN_CONFIG }}" >> $VPN_CONFIG
      shell: bash
    - id: vpn-wireguard
      if: ${{ inputs.VPN_TYPE == 'wireguard' }}
      run: bash ./script/wireguard.sh
      shell: bash
    - id: vpn-openvpn
      if: ${{ inputs.VPN_TYPE == 'openvpn' }}
      run: bash ./script/openvpn.sh
      shell: bash
    - id: vpn-l2tp
      if: ${{ inputs.VPN_TYPE == 'l2tp' }}
      run: bash ./script/l2tp.sh
      shell: bash
    - id: vpn-pptp
      if: ${{ inputs.VPN_TYPE == 'pptp' }}
      run: bash ./script/pptp.sh
      shell: bash
    - id: vpn-forticlient
      if: ${{ inputs.VPN_TYPE == 'forticlient' }}
      run: bash ./script/pptp.sh
      shell: bash
    - id: vpn-cisco
      if: ${{ inputs.VPN_TYPE == 'cisco' }}
      run: bash ./script/cisco-anyconnect.sh
      shell: bash
