# action.yml
name: 'GitHub Action VPN'
author: 'Unknow.sk'
description: 'Establish OpenVPN, PPTP, L2TP, WireGuard, FortiClient or Cisco AnyConnect VPN connection on Github Actions.'
branding:
  icon: "shield"
  color: "gray-dark"
inputs:
  VPN_OS:
    description: 'Type of OS on which the commands will be executed. Supported "ubuntu" (default).'
    default: 'ubuntu'
    required: false
  VPN_TYPE:
    description: 'Type of VPN connection. Supported "pptp", "l2tp", "wireguard", "forticlient", "cisco", or "openvpn" (default).'
    default: 'openvpn'
    required: false
  VPN_USER:
    description: 'Username for VPN connection.'
    required: true
  VPN_PASSWORD:
    description: 'Password for VPN connection.'
    required: true
  VPN_SERVER:
    description: 'Host name or IP address of VPN server.'
    required: true
  VPN_PSK:
    description: 'Shared secret key for VPN connection. Required for L2TP.'
    required: false
  VPN_CONFIG:
    description: 'Content of VPN configuration file. Required for OpenVPN and WireGuard.'
    required: false
runs:
  using: 'composite'
  steps:
    - id: vpn-l2tp
      run: bash ./script/l2tp.sh
      shell: bash
