name: Test

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - README.md


jobs:
  test:
    runs-on: ubuntu-latest
    name: L2TP Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Connect to VPN
        uses: "./"
        with:
          VPN_TYPE: l2tp
          VPN_SERVER: ${{ secrets.L2TP_SERVER }}
          VPN_USER: ${{ secrets.L2TP_USER }}
          VPN_PASSWORD: ${{ secrets.L2TP_PASSWORD }}
          VPN_PSK: ${{ secrets.L2TP_PSK }}
      - name: Check if connected
        run: curl -v ${{ secrets.L2TP_TARGET_URL }}
